### ISSUE TITLE
Blender 2.8 Compatibility?

### ISSUE THREAD

**Issue by DerekX** [Skarmory/mdl-importer#5]
Any way this add-on can be upgraded to work with Blender 2.8_?

**Comment by thorsummoner** [comment]
```Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
Warning: class IMPORT_MESH_OT_mdl contains a property which should be an annotation!
/Text:444
    assign as a type annotation: IMPORT_MESH_OT_mdl.filter_glob
Traceback (most recent call last):
  File "/Text", line 452, in <module>
  File "/Text", line 445, in register
AttributeError: 'RNA_Types' object has no attribute 'INFO_MT_file_import'
```


```
# line 445
-    bpy.types.INFO_MT_file_import.append(menu)
+    bpy.types.TOPBAR_MT_file_import.append(menu)
```

**Comment by MegatRonSwanson** [comment]
> ```
> Warning: class IMPORT_MESH_OT_mdl contains a property which should be an annotation!
> /Text:444
>     assign as a type annotation: IMPORT_MESH_OT_mdl.filter_glob
> Traceback (most recent call last):
>   File "/Text", line 452, in <module>
>   File "/Text", line 445, in register
> AttributeError: 'RNA_Types' object has no attribute 'INFO_MT_file_import'
> ```
> 
> ```
> # line 445
> -    bpy.types.INFO_MT_file_import.append(menu)
> +    bpy.types.TOPBAR_MT_file_import.append(menu)
> ```

Updated both 445 *and* 449 to topbar, no dice.
